#Container based testing
sudo: false
language: cpp
compiler: gcc
branches: 
  only:
    - master
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libxcb1-dev
      - pkg-config
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update || brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade cmake || true; fi
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC="gcc-4.9"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=":99.0"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start; fi
script:
  - $CXX --version
  - $CC --version
  - cmake -Dtest=on -Dsamples=on .
  - make
  - make check